### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by krzysztofrewak** [brewmap/brewmap#23]
Users can register via form with their email address and password OR via Facebook plugin. Probably we'll need use Sanctum + Socialite.

**Comment by krzysztofrewak** [comment]
@HerringTheCoder, how's the work going? Have you considered using Sanctum and Socialite?

**Comment by HerringTheCoder** [comment]
Sanctum is already set up with login and register fuctionality. I'll try to add socialite in the coming days.
