### ISSUE TITLE
Branches after merging pull requests

### ISSUE THREAD

**Issue by krzysztofrewak** [brewmap/brewmap#39]
I would like to ask all of you a very important question: **What are we going to do with all branches with stuff that has been already merged into development branch?** 

Right now we have like [fifteen](https://github.com/brewmap/brewmap/branches) branches and it looks like there will be one million more soon. I don't care about Github's capabilities, but it's starting to look very crowded in PHPStorm's git manager: 

![image](https://user-images.githubusercontent.com/10898728/92006265-c95b8a00-ed44-11ea-92d1-e6fc9855e657.png)

My proposition is to remove them right after every merged pull request. We could add this to Wiki after we'll decide.

**Comment by HerringTheCoder** [comment]
I don't see any point in keeping branches.
Any related future fixes would be marked as a new issue first, thus requiring a new branch by convention.
Plus, deleting branches is easily reversible anyway:
https://docs.github.com/en/github/administering-a-repository/deleting-and-restoring-branches-in-a-pull-request

**Comment by mlencki** [comment]
I also opt for deleting branches
This can be done automatically after PR merging:
https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by mateuszchodor** [comment]
I have the same opinion as the previous speakers. I don't see any point in keeping branches.

**Comment by krzysztofrewak** [comment]
@HerringTheCoder @MLencki @mateuszchodor I will set up automatic deletion of branches. Thanks!

**Comment by krzysztofrewak** [comment]
Done. I also disabled classic merging option as we agreed to squash commits on develop-branch pull requests.
