### ISSUE TITLE
Edit profile features

### ISSUE THREAD

**Issue by krzysztofrewak** [brewmap/brewmap#82]
As an authenticated user I would like to:

- [x] change my public name
- [x] change my password (with previous password confirmation)
- [x] change my email (with confirmation)
- [x] change other stuff in profile (description, avatar, things like this)

To discuss: "Edit profile" page fields should be asynchronous, eg. changing values in inputs should automatically save them in database. I would see it as forms in Blade files on one `/profile/edit` page and some calls to API within.

**Comment by kamilpiech97** [comment]
Hi, I have one question about confirmation new email. 
Confirmation with user password or email message or what?

**Comment by krzysztofrewak** [comment]
> Confirmation with user password or email message or what?

@kamilpiech97, I think that an e-mail confirmation would be OK.

**Comment by kamilpiech97** [comment]
@krzysztofrewak i have question about psalm. 
I use Carbon parser in mutator at Profile Eloquent claas and when i checked project with Psalm i have errors like this https://github.com/vimeo/psalm/issues/1325 - missing throwblocks. Do you have any solution for that or something.

**Comment by krzysztofrewak** [comment]
I would add what kind of exception is being thrown there:

```
    /**
     * @throws InvalidFormatException
     */
    public function setBirthdayAttribute($value): void
    {
        $this->attributes["birthday"] = Carbon::parse($value);
    }
```

**Comment by kamilpiech97** [comment]
The frontend we will add to new feature branch like "frontend/livewire" etc. 
I think it is good idea and we must choose livewire, laravel blades or something like Vue.js
